<script lang="ts">
	import { get } from 'svelte/store';
	import UPLD from '$lib/upld.js';
    import { apiCreatePR, apiCreateFilesAndPush, apiGetCredentials, type oAuthResponse } from '$lib/upld';
    import { onMount } from 'svelte';


	const backendBase = 'https://csgitbot.students.cs.unibo.it';
    const backendCallback = `${backendBase}/oauth/redirect?code=`;

    let urlParams;
    $: code = '';
    $: accessToken = {} as oAuthResponse;
    onMount(() => {
        urlParams = new URLSearchParams(window.location.search);
        const paramCode = urlParams.get('code');
        if (paramCode) {
            code = paramCode;
            uploadFiles(code);
        } else {
            // TODO: handle error
            console.log('no code');
        }
        console.log(code);
        
    });

    async function uploadFiles(code: string) {
        const backendUrl = `${backendCallback}${code}`;

        // TODO: set to local storage so it is seen as logged!?
        accessToken = await apiGetCredentials(code);
        const upldStore = get(UPLD);
    
        // // TODO: a better way to handle this is to use IndexedDB, or things like that.
        // // Probably will incur into errors if the user uploads too big files.
        const files = await Promise.all(upldStore.file.map(async (file, i) => {
            console.log(upldStore.file_name[i] + '---')
            // decode base 64 to file
            const content = await fetch(file);
            const blob = await content.blob();

            return new File([blob], upldStore.file_name[i]);
        }));

        try {
            const uploadResponse = await apiCreateFilesAndPush(upldStore.repo, upldStore.dir, files);
            const responses = await apiCreatePR(upldStore.repo, uploadResponse.branch_name, "Autogenerated PR");
            console.log(responses);
        } catch (error) {
            console.log(error);
        }
    }
</script>

<div>CIAO</div>

    <p> uploading </p>
    <p> uploaded </p>
    <!-- <p style="color: red"> {error.message} </p> -->